language: node_js

env:
  global:
    - CXX=g++-4.8
    - ARTIFACTS_BUCKET=ds-server-artifacts

node_js:
  - "stable"
  - "4.4.4"

matrix:
  include:
    - node_js: "4.4.4"
      os: osx

script:
  - npm run ci
  - chmod 555 scripts/package.sh && scripts/package.sh

after_script:
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"

deploy:
  - provider: s3
    access_key_id:
      secure: "Tl42ZPo3T6LpJ24QBfs8ZAOlYZr/8NgfOPhbsWf0In6ro4cEgOaq3JFSooP/eozSquYs1scpgpSv48a7dvHv4Ranm/toO9sxPgMs95OnjJCMSY2//oM+rStRAJTMLoeB2OWWgs1oSGkiuFJASXalTueVGOlVMFDsQ8MEHOWIv32vXFG6P3SgtO5GiTAvtYZEVnTdUSgZEni5dyWMRwP6ugMsl1WEBIBTE8xNHnRIPBD/sQk7pgWYp/Q4FQZ5NMcG7oegF4DLsxvUP5XVQIFABD/8G19Y/ABN9yCsvmXlywTZ2xROQts6Qpwq0w+qXMYHawJA2TeHRG0InfEJRXvKC62XD0fzpzJxASDsZa5oEfTtl2FY4MvQsWZnvgGLLs/nWkPPJNOphxVjX0x3xPPUydsNGYGty5f2tTjWx2axF+gOYY3yAFAXCLCx6JM6cKY7QlEUvG/v+okB9foJSnTl+POS16giCiBTNmi1qo0J3kvdb6zSa4JkvO5ZNq5VCmLRN+G0xh1IYuZaTwaQQz9bntdRm+IOBjGCExR5qhT5gClYhM8DHrQXl0d/aFfvtvw89ljLvPQ+rZGeSjqM03q3u1KqLhheF0px7cSPQ1PmSPtY4aO4JIR3Aw/6Szo5a4crXyze6qzkbboUaVZQTXJauuna35AkTTFnqwkHOuAys3g="
    secret_access_key:
      secure: "eEtp6gpC9d/abC/RRaBjcIKylNz2E52xLXAvshDJ03RrBg5IkXFlaP/JalCqXnh755QpHRpyUsAT1D3I9bsELCUaNZyldmLr/TeYQUQhYkDqww/HPJk8i3a6tkFP8NgdrM+2XNF2CQMPxnPoPRg99gKv/YpISaWvsMvgvFlj7tXuhL8iKIe0LDlQTSg5ICfo4a2HEfH8/6wGMBf+uWkpJ8v3h2IxjI2JcjpW2Zg+wc8LekZc1jHLp2DAj0G+pZ499LedpqF5wjgqMIMseF+DWRkUTD5GPlWtbn/nfBodSW4TeWPIyp+QgPX7zMbmt7CCtIZBkfqzCEVFGTkYkfYler9tC9RHDdzIr8tjNP25j9c9IQ4lh+i03xGEfYEg0PIXVxtg5yDm7SZY7Kx8weBnkuNMMss1VcTXTSAuIOmUC4+8BBjhl0UWjtIElAsvUD6NLbgHS9N5eHGVHrpck9WJXjZykJF/+g3ONQyeI9T46OaJ+K5zmGBLnx3a4xNa4oZB11UzgXXuzsUFFratzzyhUm5V0nh4uADXiQVoWTPKT9I9cI7q8ZHL4C0Zocb8faSgdWpqbfk6zX/K/wcaleqgmz3y/RUV0JBZvYx4ckJr4wWT+U3Opy6nIkWA0zyTeJwjpYEFCngmfopAvG/byt+9XCm1WOsDrE1H/fbfK52r1qQ="
    bucket: ds-server-artifacts
    skip_cleanup: true
    acl: public_read
    upload-dir: $TRAVIS_REPO_SLUG
  - provider: releases
    api_key:
      secure: "Nza9Tduc8r2OUTXf/DVX78mL1OejgpBaOo/nZ1zJxco6v/fXtoHYjfplkqUW/bloZkeS2w88dG5fLreuQkwSQ/Zod6S0An7qTHaJ/sLN1ivVPzGoW+lwI/xvF+w11INpmQzkCQmGmsnnUzDCSyNYGluW+hZdCshpQ6ZWd3hbNKU="
    file: "$( ls build/* | grep '/deepstream.io-[^-]*-'[^-]*-[mac:linux] )"
    on:
      tags: true

plugins:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8