os:
  - Visual Studio 2015

platform:
  - x64

install:
  - ps: Install-Product node 4.4.4
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test
  - scripts\package.bat

after_build:
  - mv build\* .

# Environment variable needs to change
environment:
  MEMCACHED_URL: 54.93.77.53:11211

artifacts:
  - path: /*\*.zip/

deploy:

  - provider: S3
    access_key_id:
      secure: cq7lgQP04314hwXwM2l0yiUKRcOkwHeKkDHFULrThxE=
    secret_access_key:
      secure: AMUWZVZ4o7lS6f5ogqxTTCqDUR/TYEmPaVXzb7yRRyFUTF/zQFnZHYk1G/j7ie8/
    bucket: ds-server-artifacts
    folder: $(APPVEYOR_REPO_NAME)

  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Release description'
    auth_token:
      secure: "JVNBKA2Ih39BHg+vfsB8pg+s4KIpFBAO6iqKE7aOhSWIUUziqX4HaAxBM0KaXYAakLMQkV9bURaiNi7jKnxMbXjHUTiUNHPBDu6Q0r6jtJhYMRj4puWzVVjXBsQXcT+ppbNsLI7F6fa1R7MKSQFAHZP2XJDQEsmp936Z5XGAbkvoX+E+aGzoxLiQincRb0DGvJrmJRjzIMz3bmX0vsW1AYDgPefCCwDdIgeDyoba3jBXyQz4LqNL9iHgW4+ewcG7JpG5TntaxZpJTaQdv6Pdewf/phsF9iDROr2UfIW6IA2GlmpK4osjXegRNCw9KcIrbJG/i2Hy4hPGuzfI29UQh+manH/1DYdh3O9GZJPR/23aiXxfOujAlJC10CNLOee3xEA77NTr3LONfkgrrvMNpgHKf9++3YqCCXFCNPdf9wQZGkw9OljuyUS8vv+nLI8JxYyONM3vwsvpwYvv0Er8w4Xr2TCJKTxP9MRYGfrEERsal1BqEU7UG0kzKlUGpPQvPTvMyInEppN8kYAYboKI/f6K2HWw00259sjzPpfTYenvstgEPXF8D+uRmo+FJHYluwU/96G/bg8tFhLB+9PKTl9LSNkAx3jpmu1bgCsE9yq51ZbVYMLBjUedrJZNGIajKvRJ/r/+5wtmPIWrUprZ5N8G0hwAm5qNzMcJyO4Cr+c="
    artifact: /build\/.*\/deepstream.io-[^-]*-'[^-]*-windows/
    draft: true
    on:
      branch: master
      appveyor_repo_tag: true

build: off